try{
s_P("syj4");
var s_nHb={Uwa:["BC","AD"],vVa:["Before Christ","Anno Domini"],PVa:"JFMAMJJASOND".split(""),XVa:"JFMAMJJASOND".split(""),ika:"January February March April May June July August September October November December".split(" "),O1:"January February March April May June July August September October November December".split(" "),ixa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),lxa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),oxa:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
YVa:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),kxa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),mxa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),QVa:"SMTWTFS".split(""),y9:"SMTWTFS".split(""),jxa:["Q1","Q2","Q3","Q4"],gxa:["1st quarter","2nd quarter","3rd quarter","4th quarter"],Rwa:["AM","PM"],NV:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],WQ:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],Twa:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],PV:6,qxa:[5,6],q9:5},
s_0w=s_nHb;
s_0w={Uwa:["BC","AD"],vVa:["Before Christ","Anno Domini"],PVa:"JFMAMJJASOND".split(""),XVa:"JFMAMJJASOND".split(""),ika:"January February March April May June July August September October November December".split(" "),O1:"January February March April May June July August September October November December".split(" "),ixa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),lxa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),oxa:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),YVa:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
kxa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),mxa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),QVa:"SMTWTFS".split(""),y9:"SMTWTFS".split(""),jxa:["Q1","Q2","Q3","Q4"],gxa:["1st quarter","2nd quarter","3rd quarter","4th quarter"],Rwa:["am","pm"],NV:["EEEE, d MMMM y","d MMMM y","d MMM y","dd/MM/y"],WQ:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],Twa:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],PV:0,qxa:[5,6],q9:3};
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var s_oHb=/^(\d{4})(?:(?:-?(\d{2})(?:-?(\d{2}))?)|(?:-?(\d{3}))|(?:-?W(\d{2})(?:-?([1-7]))?))?$/,s_pHb=/^(\d{2})(?::?(\d{2})(?::?(\d{2})(\.\d+)?)?)?$/,s_qHb=/Z|(?:([-+])(\d{2})(?::?(\d{2}))?)$/,s_rHb=function(a,b){switch(b){case 1:return 0!=a%4||0==a%100&&0!=a%400?28:29;case 5:case 8:case 10:case 3:return 30}return 31},s_tHb=function(a,b){b=s_Jc(b);var c=-1==b.indexOf("T")?" ":"T";b=b.split(c);if((c=s_sHb(a,b[0]))&&!(c=2>b.length)){b=b[1];c=b.match(s_qHb);if(c)if(b=b.substring(0,b.length-c[0].length),
"Z"===c[0])var d=0;else d=60*Number(c[2])+Number(c[3]),d*="-"==c[1]?1:-1;if(b=b.match(s_pHb)){if(c){c=a.getYear();var e=a.getMonth(),f=a.getDate();a.setTime(Date.UTC(c,e,f,Number(b[1]),Number(b[2])||0,Number(b[3])||0,b[4]?1E3*Number(b[4]):0)+6E4*d)}else a.setHours(Number(b[1])),a.setMinutes(Number(b[2])||0),a.setSeconds(Number(b[3])||0),a.setMilliseconds(b[4]?1E3*Number(b[4]):0);c=!0}else c=!1}return c},s_sHb=function(a,b){var c=b.match(s_oHb);if(!c)return!1;var d=Number(c[2]),e=Number(c[3]),f=Number(c[4]);
b=Number(c[5]);var g=Number(c[6])||1;a.setFullYear(Number(c[1]));f?(a.setDate(1),a.setMonth(0),a.add(new s_1w("d",f-1))):b?(a.setMonth(0),a.setDate(1),c=a.getDay()||7,a.add(new s_1w("d",(4>=c?1-c:8-c)+(Number(g)+7*(Number(b)-1))-1))):(d&&(a.setDate(1),a.setMonth(d-1)),e&&a.setDate(e));return!0},s_1w=function(a,b,c,d,e,f){"string"===typeof a?(this.Aa="y"==a?b:0,this.wa="m"==a?b:0,this.Mm="d"==a?b:0,this.hours="h"==a?b:0,this.minutes="n"==a?b:0,this.Fp="s"==a?b:0):(this.Aa=a||0,this.wa=b||0,this.Mm=
c||0,this.hours=d||0,this.minutes=e||0,this.Fp=f||0)};s_a=s_1w.prototype;
s_a.Pf=function(a){var b=Math.min(this.Aa,this.wa,this.Mm,this.hours,this.minutes,this.Fp),c=Math.max(this.Aa,this.wa,this.Mm,this.hours,this.minutes,this.Fp);if(0>b&&0<c)return null;if(!a&&0==b&&0==c)return"PT0S";c=[];0>b&&c.push("-");c.push("P");(this.Aa||a)&&c.push(Math.abs(this.Aa)+"Y");(this.wa||a)&&c.push(Math.abs(this.wa)+"M");(this.Mm||a)&&c.push(Math.abs(this.Mm)+"D");if(this.hours||this.minutes||this.Fp||a)c.push("T"),(this.hours||a)&&c.push(Math.abs(this.hours)+"H"),(this.minutes||a)&&
c.push(Math.abs(this.minutes)+"M"),(this.Fp||a)&&c.push(Math.abs(this.Fp)+"S");return c.join("")};s_a.equals=function(a){return a.Aa==this.Aa&&a.wa==this.wa&&a.Mm==this.Mm&&a.hours==this.hours&&a.minutes==this.minutes&&a.Fp==this.Fp};s_a.clone=function(){return new s_1w(this.Aa,this.wa,this.Mm,this.hours,this.minutes,this.Fp)};s_a.JC=function(){return 0==this.Aa&&0==this.wa&&0==this.Mm&&0==this.hours&&0==this.minutes&&0==this.Fp};
s_a.add=function(a){this.Aa+=a.Aa;this.wa+=a.wa;this.Mm+=a.Mm;this.hours+=a.hours;this.minutes+=a.minutes;this.Fp+=a.Fp};
var s_2w=function(a,b,c){"number"===typeof a?(this.date=s_uHb(a,b||0,c||1),s_vHb(this,c||1)):s_na(a)?(this.date=s_uHb(a.getFullYear(),a.getMonth(),a.getDate()),s_vHb(this,a.getDate())):(this.date=new Date(s_Oa()),a=this.date.getDate(),this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),s_vHb(this,a))},s_uHb=function(a,b,c){b=new Date(a,b,c);0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b};s_a=s_2w.prototype;s_a.Eaa=s_0w.PV;s_a.FX=s_0w.q9;
s_a.clone=function(){var a=new s_2w(this.date);a.Eaa=this.Eaa;a.FX=this.FX;return a};s_a.getFullYear=function(){return this.date.getFullYear()};s_a.getYear=function(){return this.getFullYear()};s_a.getMonth=function(){return this.date.getMonth()};s_a.getDate=function(){return this.date.getDate()};s_a.getTime=function(){return this.date.getTime()};s_a.getDay=function(){return this.date.getDay()};s_a.xY=function(){return((this.getDay()+6)%7-this.Eaa+7)%7};s_a.getUTCFullYear=function(){return this.date.getUTCFullYear()};
s_a.getUTCMonth=function(){return this.date.getUTCMonth()};s_a.getUTCDate=function(){return this.date.getUTCDate()};s_a.getUTCDay=function(){return this.date.getDay()};s_a.getUTCHours=function(){return this.date.getUTCHours()};s_a.getUTCMinutes=function(){return this.date.getUTCMinutes()};s_a.ZX=function(){return this.Eaa};s_a.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};s_a.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};s_a.setFullYear=function(a){this.date.setFullYear(a)};
s_a.setYear=function(a){this.setFullYear(a)};s_a.setMonth=function(a){this.date.setMonth(a)};s_a.setDate=function(a){this.date.setDate(a)};s_a.setTime=function(a){this.date.setTime(a)};s_a.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};s_a.setUTCMonth=function(a){this.date.setUTCMonth(a)};s_a.setUTCDate=function(a){this.date.setUTCDate(a)};s_a.Lta=function(a){this.Eaa=a};
s_a.add=function(a){if(a.Aa||a.wa){var b=this.getMonth()+a.wa+12*a.Aa,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);var d=Math.min(s_rHb(c,b),this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.Mm&&(b=new Date(this.getYear(),this.getMonth(),this.getDate(),12),a=new Date(b.getTime()+864E5*a.Mm),this.setDate(1),this.setFullYear(a.getFullYear()),this.setMonth(a.getMonth()),this.setDate(a.getDate()),s_vHb(this,a.getDate()))};
s_a.Pf=function(a){return[this.getFullYear(),s_qd(this.getMonth()+1,2),s_qd(this.getDate(),2)].join(a?"-":"")};s_a.equals=function(a){return!(!a||this.getYear()!=a.getYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};s_a.toString=function(){return this.Pf()};var s_vHb=function(a,b){a.getDate()!=b&&(b=a.getDate()<b?1:-1,a.date.setUTCHours(a.date.getUTCHours()+b))};s_2w.prototype.valueOf=function(){return this.date.valueOf()};
var s_3w=function(a,b,c,d,e,f,g){this.date="number"===typeof a?new Date(a,b||0,c||1,d||0,e||0,f||0,g||0):new Date(a&&a.getTime?a.getTime():s_Oa())};s_p(s_3w,s_2w);s_a=s_3w.prototype;s_a.getHours=function(){return this.date.getHours()};s_a.getMinutes=function(){return this.date.getMinutes()};s_a.getSeconds=function(){return this.date.getSeconds()};s_a.getMilliseconds=function(){return this.date.getMilliseconds()};s_a.getUTCDay=function(){return this.date.getUTCDay()};s_a.getUTCHours=function(){return this.date.getUTCHours()};
s_a.getUTCMinutes=function(){return this.date.getUTCMinutes()};s_a.getUTCSeconds=function(){return this.date.getUTCSeconds()};s_a.getUTCMilliseconds=function(){return this.date.getUTCMilliseconds()};s_a.setHours=function(a){this.date.setHours(a)};s_a.setMinutes=function(a){this.date.setMinutes(a)};s_a.setSeconds=function(a){this.date.setSeconds(a)};s_a.setMilliseconds=function(a){this.date.setMilliseconds(a)};s_a.setUTCHours=function(a){this.date.setUTCHours(a)};s_a.setUTCMinutes=function(a){this.date.setUTCMinutes(a)};
s_a.setUTCSeconds=function(a){this.date.setUTCSeconds(a)};s_a.setUTCMilliseconds=function(a){this.date.setUTCMilliseconds(a)};s_a.add=function(a){s_2w.prototype.add.call(this,a);a.hours&&this.setUTCHours(this.date.getUTCHours()+a.hours);a.minutes&&this.setUTCMinutes(this.date.getUTCMinutes()+a.minutes);a.Fp&&this.setUTCSeconds(this.date.getUTCSeconds()+a.Fp)};
s_a.Pf=function(a){var b=s_2w.prototype.Pf.call(this,a);return a?b+"T"+s_qd(this.getHours(),2)+":"+s_qd(this.getMinutes(),2)+":"+s_qd(this.getSeconds(),2):b+"T"+s_qd(this.getHours(),2)+s_qd(this.getMinutes(),2)+s_qd(this.getSeconds(),2)};s_a.equals=function(a){return this.getTime()==a.getTime()};s_a.toString=function(){return this.Pf()};s_a.clone=function(){var a=new s_3w(this.date);a.Lta(this.ZX());a.FX=this.FX;return a};var s_4w=function(a){var b=new s_3w(2E3);return s_tHb(b,a)?b:null};

s_h().wa();

}catch(e){_DumpException(e)}
try{
var s_wHb=function(a){return s_rHb(a.getFullYear(),a.getMonth())},s_xHb=function(a,b,c,d,e){a=new Date(a,b,c);d=void 0!==d?d:3;e=e||0;b=((a.getDay()+6)%7-e+7)%7;return a.valueOf()+864E5*((d-e+7)%7-b)},s_yHb=function(a,b){return a.getTime()-b.getTime()};s_P("syj5");
var s_zHb=function(){},s_5w=function(a){if("number"==typeof a){var b=new s_zHb;b.Da=a;var c=a;if(0==c)c="Etc/GMT";else{var d=["Etc/GMT",0>c?"-":"+"];c=Math.abs(c);d.push(Math.floor(c/60)%100);c%=60;0!=c&&d.push(":",s_qd(c,2));c=d.join("")}b.Ba=c;c=a;0==c?c="UTC":(d=["UTC",0>c?"+":"-"],c=Math.abs(c),d.push(Math.floor(c/60)%100),c%=60,0!=c&&d.push(":",c),c=d.join(""));a=s_AHb(a);b.Ca=[c,c];b.wa={vAc:a,ZVa:a};b.Aa=[];return b}b=new s_zHb;b.Ba=a.id;b.Da=-a.std_offset;b.Ca=a.names;b.wa=a.names_ext;b.Aa=
a.transitions;return b},s_AHb=function(a){var b=["GMT"];b.push(0>=a?"+":"-");a=Math.abs(a);b.push(s_qd(Math.floor(a/60)%100,2),":",s_qd(a%60,2));return b.join("")},s_BHb=function(a,b){b=Date.UTC(b.getUTCFullYear(),b.getUTCMonth(),b.getUTCDate(),b.getUTCHours(),b.getUTCMinutes())/36E5;for(var c=0;c<a.Aa.length&&b>=a.Aa[c];)c+=2;return 0==c?0:a.Aa[c-1]},s_CHb=function(a,b){return a.Da-s_BHb(a,b)},s_DHb=function(a,b){return 0<s_BHb(a,b)};
var s_6w=function(a,b){this.Aa=[];this.wa=b||s_0w;"number"==typeof a?s_EHb(this,a):s_FHb(this,a)},s_GHb=[/^'(?:[^']|'')*('|$)/,/^(?:G+|y+|Y+|M+|k+|S+|E+|a+|h+|K+|H+|c+|L+|Q+|d+|m+|s+|v+|V+|w+|z+|Z+)/,/^[^'GyYMkSEahKHcLQdmsvVwzZ]+/],s_HHb=function(a){return a.getHours?a.getHours():0},s_FHb=function(a,b){for(s_IHb&&(b=b.replace(/\u200f/g,""));b;){for(var c=b,d=0;d<s_GHb.length;++d){var e=b.match(s_GHb[d]);if(e){var f=e[0];b=b.substring(f.length);0==d&&("''"==f?f="'":(f=f.substring(1,"'"==e[1]?f.length-
1:f.length),f=f.replace(/''/g,"'")));a.Aa.push({text:f,type:d});break}}if(c===b)throw Error("Sd`"+b);}};
s_6w.prototype.format=function(a,b){if(!a)throw Error("Td");var c=b?6E4*(a.getTimezoneOffset()-s_CHb(b,a)):0,d=c?new Date(a.getTime()+c):a,e=d;b&&d.getTimezoneOffset()!=a.getTimezoneOffset()&&(e=6E4*(d.getTimezoneOffset()-a.getTimezoneOffset()),d=new Date(d.getTime()+e),c+=0<c?-864E5:864E5,e=new Date(a.getTime()+c));c=[];for(var f=0;f<this.Aa.length;++f){var g=this.Aa[f].text;1==this.Aa[f].type?c.push(s_JHb(this,g,a,d,e,b)):c.push(g)}return c.join("")};
var s_EHb=function(a,b){if(4>b)var c=a.wa.NV[b];else if(8>b)c=a.wa.WQ[b-4];else if(12>b)c=a.wa.Twa[b-8],c=c.replace("{1}",a.wa.NV[b-8]),c=c.replace("{0}",a.wa.WQ[b-8]);else{s_EHb(a,10);return}s_FHb(a,c)},s_7w=function(a,b){b=String(b);a=a.wa||s_0w;if(void 0!==a.sxa){for(var c=[],d=0;d<b.length;d++){var e=b.charCodeAt(d);c.push(48<=e&&57>=e?String.fromCharCode(a.sxa+e-48):b.charAt(d))}b=c.join("")}return b},s_IHb=!1,s_8w=function(a){if(!(a.getHours&&a.getSeconds&&a.getMinutes))throw Error("Ud");},
s_JHb=function(a,b,c,d,e,f){var g=b.length;switch(b.charAt(0)){case "G":return c=0<d.getFullYear()?1:0,4<=g?a.wa.vVa[c]:a.wa.Uwa[c];case "y":return c=d.getFullYear(),0>c&&(c=-c),2==g&&(c%=100),s_7w(a,s_qd(c,g));case "Y":return c=d.getMonth(),e=d.getDate(),c=s_xHb(d.getFullYear(),c,e,a.wa.q9,a.wa.PV),c=(new Date(c)).getFullYear(),0>c&&(c=-c),2==g&&(c%=100),s_7w(a,s_qd(c,g));case "M":a:switch(c=d.getMonth(),g){case 5:g=a.wa.PVa[c];break a;case 4:g=a.wa.ika[c];break a;case 3:g=a.wa.ixa[c];break a;default:g=
s_7w(a,s_qd(c+1,g))}return g;case "k":return s_8w(e),c=s_HHb(e)||24,s_7w(a,s_qd(c,g));case "S":return s_7w(a,(e.getMilliseconds()/1E3).toFixed(Math.min(3,g)).substr(2)+(3<g?s_qd(0,g-3):""));case "E":return c=d.getDay(),4<=g?a.wa.oxa[c]:a.wa.kxa[c];case "a":return s_8w(e),g=s_HHb(e),a.wa.Rwa[12<=g&&24>g?1:0];case "h":return s_8w(e),c=s_HHb(e)%12||12,s_7w(a,s_qd(c,g));case "K":return s_8w(e),c=s_HHb(e)%12,s_7w(a,s_qd(c,g));case "H":return s_8w(e),c=s_HHb(e),s_7w(a,s_qd(c,g));case "c":a:switch(c=d.getDay(),
g){case 5:g=a.wa.y9[c];break a;case 4:g=a.wa.YVa[c];break a;case 3:g=a.wa.mxa[c];break a;default:g=s_7w(a,s_qd(c,1))}return g;case "L":a:switch(c=d.getMonth(),g){case 5:g=a.wa.XVa[c];break a;case 4:g=a.wa.O1[c];break a;case 3:g=a.wa.lxa[c];break a;default:g=s_7w(a,s_qd(c+1,g))}return g;case "Q":return c=Math.floor(d.getMonth()/3),4>g?a.wa.jxa[c]:a.wa.gxa[c];case "d":return s_7w(a,s_qd(d.getDate(),g));case "m":return s_8w(e),s_7w(a,s_qd(e.getMinutes(),g));case "s":return s_8w(e),s_7w(a,s_qd(e.getSeconds(),
g));case "v":return g=f||s_5w(c.getTimezoneOffset()),g.Ba;case "V":return a=f||s_5w(c.getTimezoneOffset()),2>=g?a.Ba:s_DHb(a,c)?void 0!==a.wa.wnb?a.wa.wnb:a.wa.DST_GENERIC_LOCATION:void 0!==a.wa.ZVa?a.wa.ZVa:a.wa.STD_GENERIC_LOCATION;case "w":return c=e.getMonth(),d=e.getDate(),c=s_xHb(e.getFullYear(),c,d,a.wa.q9,a.wa.PV),c=Math.floor(Math.round((c-(new Date((new Date(c)).getFullYear(),0,1)).valueOf())/864E5)/7)+1,s_7w(a,s_qd(c,g));case "z":return a=f||s_5w(c.getTimezoneOffset()),4>g?a.Ca[s_DHb(a,
c)?2:0]:a.Ca[s_DHb(a,c)?3:1];case "Z":return d=f||s_5w(c.getTimezoneOffset()),4>g?(g=-s_CHb(d,c),a=[0>g?"-":"+"],g=Math.abs(g),a.push(s_qd(Math.floor(g/60)%100,2),s_qd(g%60,2)),g=a.join("")):g=s_7w(a,s_AHb(s_CHb(d,c))),g;default:return""}};

s_h().wa();

}catch(e){_DumpException(e)}
try{
s_P("syj6");
var s_9w={z9:"y",fWa:"y G",rxa:"MMM y",lka:"MMMM y",gWa:"MM/y",RV:"MMM d",v9:"MMMM dd",kka:"M/d",jka:"MMMM d",w9:"MMM d, y",LJ:"EEE, MMM d",pxa:"EEE, MMM d, y",pVa:"d",Bob:"MMM d, h:mm a zzzz"};s_9w={z9:"y",fWa:"y G",rxa:"MMM y",lka:"MMMM y",gWa:"MM/y",RV:"d MMM",v9:"dd MMMM",kka:"dd/MM",jka:"d MMMM",w9:"d MMM y",LJ:"EEE, d MMM",pxa:"EEE, d MMM y",pVa:"d",Bob:"d MMM, HH:mm zzzz"};

s_h().wa();

}catch(e){_DumpException(e)}
try{
s_P("synn");
var s_WA=function(){};s_Fb(s_WA);s_WA.prototype.wa=0;var s_L2b=function(a){return":"+(a.wa++).toString(36)};

s_h().wa();

}catch(e){_DumpException(e)}
try{
s_P("syno");
var s_XA=function(a){s_$g.call(this);this.zc=a||s_5e();this.Ob=s_M2b;this.wd=null;this.Ph=!1;this.yb=null;this.Oa=void 0;this.Ga=this.Ba=this.Re=this.Cb=null;this.kf=!1};s_p(s_XA,s_$g);s_XA.prototype.hh=s_WA.Jb();var s_M2b=null;s_XA.prototype.getId=function(){return this.wd||(this.wd=s_L2b(this.hh))};s_XA.prototype.Fa=function(){return this.yb};s_XA.prototype.Ev=function(a){return this.yb?this.zc.Ev(a,this.yb):null};
var s_YA=function(a){a.Oa||(a.Oa=new s_fi(a));return a.Oa},s_N2b=function(a,b){if(a==b)throw Error("Ie");if(b&&a.Re&&a.wd&&a.Re.Yr(a.wd)&&a.Re!=b)throw Error("Ie");a.Re=b;s_XA.uc.s0.call(a,b)};s_XA.prototype.getParent=function(){return this.Re};s_XA.prototype.s0=function(a){if(this.Re&&this.Re!=a)throw Error("Je");s_XA.uc.s0.call(this,a)};s_XA.prototype.Gk=function(){this.yb=s_Mf(this.zc,"DIV")};s_XA.prototype.render=function(a){s_O2b(this,a)};
var s_O2b=function(a,b,c){if(a.Ph)throw Error("Ke");a.yb||a.Gk();b?b.insertBefore(a.yb,c||null):a.zc.Ce().body.appendChild(a.yb);a.Re&&!a.Re.Ph||a.xg()};s_a=s_XA.prototype;s_a.Xe=function(a){if(this.Ph)throw Error("Ke");if(a&&this.fca(a)){this.kf=!0;var b=s_4e(a);this.zc&&this.zc.Ce()==b||(this.zc=s_5e(a));this.Fl(a);this.xg()}else throw Error("Le");};s_a.fca=function(){return!0};s_a.Fl=function(a){this.yb=a};s_a.xg=function(){this.Ph=!0;s_ZA(this,function(a){!a.Ph&&a.Fa()&&a.xg()})};
s_a.Gl=function(){s_ZA(this,function(a){a.Ph&&a.Gl()});this.Oa&&this.Oa.removeAll();this.Ph=!1};s_a.nb=function(){this.Ph&&this.Gl();this.Oa&&(this.Oa.dispose(),delete this.Oa);s_ZA(this,function(a){a.dispose()});!this.kf&&this.yb&&s_uf(this.yb);this.Re=this.Cb=this.yb=this.Ga=this.Ba=null;s_XA.uc.nb.call(this)};s_a.Ek=function(){return this.Cb};s_a.Xi=function(a,b){this.eca(a,s__A(this),b)};
s_a.eca=function(a,b,c){if(a.Ph&&(c||!this.Ph))throw Error("Ke");if(0>b||b>s__A(this))throw Error("Me");this.Ga&&this.Ba||(this.Ga={},this.Ba=[]);if(a.getParent()==this){var d=a.getId();this.Ga[d]=a;s_1b(this.Ba,a)}else s_pc(this.Ga,a.getId(),a);s_N2b(a,this);s__b(this.Ba,a,b);a.Ph&&this.Ph&&a.getParent()==this?(c=this.hf(),b=c.childNodes[b]||null,b!=a.Fa()&&c.insertBefore(a.Fa(),b)):c?(this.yb||this.Gk(),b=s_0A(this,b+1),s_O2b(a,this.hf(),b?b.yb:null)):this.Ph&&!a.Ph&&a.yb&&a.yb.parentNode&&1==a.yb.parentNode.nodeType&&
a.xg()};s_a.hf=function(){return this.yb};var s_1A=function(a){null==a.Ob&&(a.Ob=s_Bh(a.Ph?a.yb:a.zc.Ce().body));return a.Ob},s__A=function(a){return a.Ba?a.Ba.length:0};s_XA.prototype.Yr=function(a){return this.Ga&&a?s_qc(this.Ga,a)||null:null};var s_0A=function(a,b){return a.Ba?a.Ba[b]||null:null},s_ZA=function(a,b,c){a.Ba&&s_q(a.Ba,b,c)};
s_XA.prototype.removeChild=function(a,b){if(a){var c="string"===typeof a?a:a.getId();a=this.Yr(c);c&&a&&(s_oc(this.Ga,c),s_1b(this.Ba,a),b&&(a.Gl(),a.yb&&s_uf(a.yb)),s_N2b(a,null))}if(!a)throw Error("Ne");return a};var s_P2b=function(a){return a.removeChild(s_0A(a,0),!0)},s_Q2b=function(a){for(var b=[];a.Ba&&0!=a.Ba.length;)b.push(s_P2b(a))};

s_h().wa();

}catch(e){_DumpException(e)}
try{
s_P("syqs");
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var s_Qjc=new s_2w(0,0,1),s_Rjc=new s_2w(9999,11,31);

s_h().wa();

}catch(e){_DumpException(e)}
try{
var s_Sjc=function(a){this.wa=a.getStartDate().clone();this.Aa=Number(a.wa.Pf())};s_p(s_Sjc,s_yg);s_Sjc.prototype.next=function(){if(Number(this.wa.Pf())>this.Aa)throw s_xg;var a=this.wa.clone();this.wa.add(new s_1w("d",1));return a};var s_Tjc=function(){this.Aa=s_Qjc;this.wa=s_Rjc};s_Tjc.prototype.getStartDate=function(){return this.Aa};s_Tjc.prototype.contains=function(a){return a.valueOf()>=this.Aa.valueOf()&&a.valueOf()<=this.wa.valueOf()};s_Tjc.prototype.iterator=function(){return new s_Sjc(this)};
s_P("syqr");
var s_Ujc=function(a,b){this.wa=a;this.zc=b||s_5e()};
s_Ujc.prototype.Ea=function(a,b,c,d){b?(d=s_Mf(this.zc,"TD"),d.colSpan=c?1:2,s_OE(this,d,"\u00ab",this.wa+"-previousMonth"),a.appendChild(d),d=s_Mf(this.zc,"TD"),d.colSpan=c?6:5,d.className=this.wa+"-monthyear",a.appendChild(d),d=s_Mf(this.zc,"TD"),s_OE(this,d,"\u00bb",this.wa+"-nextMonth"),a.appendChild(d)):(c=s_Mf(this.zc,"TD"),c.colSpan=5,s_OE(this,c,"\u00ab",this.wa+"-previousMonth"),s_OE(this,c,"",this.wa+"-month"),s_OE(this,c,"\u00bb",this.wa+"-nextMonth"),b=s_Mf(this.zc,"TD"),b.colSpan=3,s_OE(this,
b,"\u00ab",this.wa+"-previousYear"),s_OE(this,b,"",this.wa+"-year"),s_OE(this,b,"\u00bb",this.wa+"-nextYear"),d.indexOf("y")<d.indexOf("m")?(a.appendChild(b),a.appendChild(c)):(a.appendChild(c),a.appendChild(b)))};
s_Ujc.prototype.Ba=function(a,b){var c=s_Mf(this.zc,"TD");c.colSpan=b?2:3;c.className=this.wa+"-today-cont";s_OE(this,c,"Today",this.wa+"-today-btn");a.appendChild(c);c=s_Mf(this.zc,"TD");c.colSpan=b?4:3;a.appendChild(c);c=s_Mf(this.zc,"TD");c.colSpan=2;c.className=this.wa+"-none-cont";s_OE(this,c,"None",this.wa+"-none-btn");a.appendChild(c)};var s_OE=function(a,b,c,d){var e=[a.wa+"-btn"];d&&e.push(d);d=s_Mf(a.zc,"BUTTON");d.className=e.join(" ");d.appendChild(s_Nf(a.zc,c));b.appendChild(d)};
var s_PE=function(a,b,c,d){s_XA.call(this,c);this.Ca=b||s_0w;this.Gc=this.Ca.mxa;this.Df=new s_6w("d",this.Ca);new s_6w("dd",this.Ca);this.Wg=new s_6w("w",this.Ca);this.Ig=new s_6w("d MMM",this.Ca);this.Rb=new s_6w(s_9w.z9||"y",this.Ca);this.Qf=new s_6w(s_9w.lka||"MMMM y",this.Ca);this.Wc=d||new s_Ujc(this.Vh(),this.zc);this.Aa=new s_2w(a);this.Aa.FX=this.Ca.q9;this.Aa.Lta(this.Ca.PV);this.wa=this.Aa.clone();this.wa.setDate(1);this.wb="      ".split(" ");this.wb[this.Ca.qxa[0]]=this.Vh()+"-wkend-start";
this.wb[this.Ca.qxa[1]]=this.Vh()+"-wkend-end";this.Ra={};this.Ka=[];this.Vb=0};s_p(s_PE,s_XA);s_a=s_PE.prototype;s_a.Vta=!0;s_a.RUa=new s_Tjc;s_a.bua=!0;s_a.cua=!0;s_a.zka=!0;s_a.aua=!0;s_a.OSa=!1;s_a.Vla=null;s_a.mma=null;s_a.lma=null;s_a.kma=null;s_a.Aub=s_WA.Jb();s_a.Vh=function(){return"goog-date-picker"};
var s_Wjc=function(a){a.OSa=!0;s_Vjc(a);s_QE(a)},s_Yjc=function(a){a.bua=!1;s_Vjc(a);s_Xjc(a);s_QE(a)},s__jc=function(a,b){a.zka=b;a.Gb&&s_Zjc(a)},s_Zjc=function(a){s_M(a.kb,a.aua);s_M(a.Gb,a.zka);s_M(a.Ue,a.aua||a.zka)};s_a=s_PE.prototype;s_a.ZOa=function(){this.wa.add(new s_1w("m",-1));s_QE(this);s_0jc(this)};s_a.l_=function(){this.wa.add(new s_1w("m",1));s_QE(this);s_0jc(this)};s_a.T9b=function(){this.wa.add(new s_1w("y",-1));s_QE(this);s_0jc(this)};
s_a.RYb=function(){this.wa.add(new s_1w("y",1));s_QE(this);s_0jc(this)};s_a.Ugb=function(){this.setDate(new s_2w)};s_a.tRa=function(){this.zka&&this.setDate(null)};s_a.getDate=function(){return this.Aa&&this.Aa.clone()};s_a.setDate=function(a){s_1jc(this,a,!0)};
var s_1jc=function(a,b,c){var d=b==a.Aa||b&&a.Aa&&b.getFullYear()==a.Aa.getFullYear()&&b.getMonth()==a.Aa.getMonth(),e=b==a.Aa||d&&b.getDate()==a.Aa.getDate();a.Aa=b&&new s_2w(b);b&&(a.wa.set(a.Aa),a.wa.setFullYear(a.Aa.getFullYear()),a.wa.setDate(1));s_QE(a);c&&a.dispatchEvent(new s_2jc("select",a,a.Aa));e||a.dispatchEvent(new s_2jc("change",a,a.Aa));d||s_0jc(a)},s_Vjc=function(a){if(a.mma){for(var b=a.mma;b.firstChild;)b.removeChild(b.firstChild);a.Wc.Ea(b,a.OSa,a.bua,a.Ca.NV[0].toLowerCase());
if(a.OSa){s_RE(a,b,a.Vh()+"-previousMonth",a.ZOa);var c=s_I(a.Vh()+"-previousMonth",b);c&&(s_ho(c,"hidden",!0),c.tabIndex=-1);s_RE(a,b,a.Vh()+"-nextMonth",a.l_);if(c=s_I(a.Vh()+"-nextMonth",b))s_ho(c,"hidden",!0),c.tabIndex=-1;a.lma=s_I(a.Vh()+"-monthyear",b)}else s_RE(a,b,a.Vh()+"-previousMonth",a.ZOa),s_RE(a,b,a.Vh()+"-nextMonth",a.l_),s_RE(a,b,a.Vh()+"-month",a.Dic),s_RE(a,b,a.Vh()+"-previousYear",a.T9b),s_RE(a,b,a.Vh()+"-nextYear",a.RYb),s_RE(a,b,a.Vh()+"-year",a.bjc),a.Ea=s_I(a.Vh()+"-month",
b),a.Ya=s_5e().Ev(a.Vh()+"-year",b)}},s_RE=function(a,b,c,d){b=s_I(c,b);s_YA(a).listen(b,"click",function(e){e.preventDefault();d.call(this,e)})},s_Xjc=function(a){if(a.kma){var b=a.kma;s_qf(b);a.Wc.Ba(b,a.bua);s_RE(a,b,a.Vh()+"-today-btn",a.Ugb);s_RE(a,b,a.Vh()+"-none-btn",a.tRa);a.kb=s_I(a.Vh()+"-today-btn",b);a.Gb=s_I(a.Vh()+"-none-btn",b);s_Zjc(a)}};s_a=s_PE.prototype;
s_a.Fl=function(a){s_PE.uc.Fl.call(this,a);s_S(a,this.Vh());var b=this.zc.xe("TABLE",{role:"presentation"}),c=this.zc.xe("THEAD"),d=this.zc.xe("TBODY",{role:"grid"}),e=this.zc.xe("TFOOT");d.tabIndex=0;this.Ge=d;this.Ue=e;var f=this.zc.xe("TR",{role:"row"});f.className=this.Vh()+"-head";this.mma=f;s_Vjc(this);c.appendChild(f);this.Da=[];for(var g=0;7>g;g++){f=s_Mf(this.zc,"TR");this.Da[g]=[];for(var h=0;8>h;h++){var k=s_Mf(this.zc,0==h||0==g?"th":"td");0!=h&&0!=g||h==g?0!==g&&0!==h&&(s_fo(k,"gridcell"),
k.setAttribute("tabindex","-1")):(k.className=0==h?this.Vh()+"-week":this.Vh()+"-wday",s_fo(k,0==h?"rowheader":"columnheader"));f.appendChild(k);this.Da[g][h]=k}d.appendChild(f)}f=s_Mf(this.zc,"TR");f.className=this.Vh()+"-foot";this.kma=f;s_Xjc(this);e.appendChild(f);b.cellSpacing="0";b.cellPadding="0";b.appendChild(c);b.appendChild(d);b.appendChild(e);a.appendChild(b);s_3jc(this);s_QE(this);a.tabIndex=0};s_a.Gk=function(){s_PE.uc.Gk.call(this);this.Fl(this.Fa())};
s_a.xg=function(){s_PE.uc.xg.call(this);var a=s_YA(this);a.listen(this.Ge,"click",this.gKb);a.listen(s_4jc(this,this.Fa()),"key",this.hKb)};s_a.Gl=function(){s_PE.uc.Gl.call(this);this.Ma();for(var a in this.Ra)this.Ra[a].dispose();this.Ra={}};s_a.create=s_PE.prototype.Xe;s_a.nb=function(){s_PE.uc.nb.call(this);this.Gb=this.kb=this.Ya=this.lma=this.Ea=this.kma=this.mma=this.Ue=this.Ge=this.Da=null};
s_a.gKb=function(a){if("TD"==a.target.tagName){var b,c=-2,d=-2;for(b=a.target;b;b=b.previousSibling,c++);for(b=a.target.parentNode;b;b=b.previousSibling,d++);a=this.Ka[d][c];this.RUa.contains(a)&&this.setDate(a.clone())}};
s_a.hKb=function(a){switch(a.keyCode){case 33:a.preventDefault();var b=-1;break;case 34:a.preventDefault();b=1;break;case 37:a.preventDefault();var c=-1;break;case 39:a.preventDefault();c=1;break;case 38:a.preventDefault();c=-7;break;case 40:a.preventDefault();c=7;break;case 36:a.preventDefault();this.Ugb();break;case 46:a.preventDefault();this.tRa();break;case 13:case 32:a.preventDefault(),s_1jc(this,this.Aa,!0);default:return}this.Aa?(a=this.Aa.clone(),a.add(new s_1w(0,b,c))):(a=this.wa.clone(),
a.setDate(1));this.RUa.contains(a)&&(s_1jc(this,a,!1),this.qg.focus())};s_a.Dic=function(a){a.stopPropagation();a=[];for(var b=0;12>b;b++)a.push(this.Ca.O1[b]);s_5jc(this,this.Ea,a,this.pLb,this.Ca.O1[this.wa.getMonth()])};s_a.bjc=function(a){a.stopPropagation();a=[];for(var b=this.wa.getFullYear(),c=this.wa.clone(),d=-5;5>=d;d++)c.setFullYear(b+d),a.push(this.Rb.format(c));s_5jc(this,this.Ya,a,this.jOb,this.Rb.format(this.wa))};
s_a.pLb=function(a){a=Number(a.getAttribute("itemIndex"));this.wa.setMonth(a);s_QE(this);this.Ea.focus&&this.Ea.focus()};s_a.jOb=function(a){3==a.firstChild.nodeType&&(a=Number(a.getAttribute("itemIndex")),this.wa.setFullYear(this.wa.getFullYear()+a-5),s_QE(this));this.Ya.focus()};
var s_5jc=function(a,b,c,d,e){a.Ma();var f=s_Mf(a.zc,"DIV");f.className=a.Vh()+"-menu";a.Sa=null;for(var g=s_Mf(a.zc,"UL"),h=0;h<c.length;h++){var k=a.zc.xe("LI",null,c[h]);k.setAttribute("itemIndex",h);c[h]==e&&(a.Sa=k);g.appendChild(k)}f.appendChild(g);f.style.left=b.offsetLeft+b.parentNode.offsetLeft+"px";f.style.top=b.offsetTop+"px";f.style.width=b.clientWidth+"px";a.Ea.parentNode.appendChild(f);a.Ia=f;a.Sa||(a.Sa=g.firstChild);a.Sa.className=a.Vh()+"-menu-selected";a.$b=d;b=s_YA(a);b.listen(a.Ia,
"click",a.Dd);b.listen(s_4jc(a,a.Ia),"key",a.Pd);b.listen(a.zc.Ce(),"click",a.Ma);f.tabIndex=0;f.focus()};s_PE.prototype.Dd=function(a){a.stopPropagation();this.Ma();this.$b&&this.$b(a.target)};
s_PE.prototype.Pd=function(a){a.stopPropagation();var b=this.Sa;switch(a.keyCode){case 35:a.preventDefault();var c=b.parentNode.lastChild;break;case 36:a.preventDefault();c=b.parentNode.firstChild;break;case 38:a.preventDefault();c=b.previousSibling;break;case 40:a.preventDefault();c=b.nextSibling;break;case 13:case 9:case 0:a.preventDefault(),this.Ma(),this.$b(b)}c&&c!=b&&(b.className="",c.className=this.Vh()+"-menu-selected",this.Sa=c)};
s_PE.prototype.Ma=function(){if(this.Ia){var a=s_YA(this);a.$d(this.Ia,"click",this.Dd);a.$d(s_4jc(this,this.Ia),"key",this.Pd);a.$d(this.zc.Ce(),"click",this.Ma);s_uf(this.Ia);delete this.Ia}};
var s_QE=function(a){if(a.Fa()){var b=a.wa.clone();b.setDate(1);a.lma&&s_Df(a.lma,a.Qf.format(b));a.Ea&&s_Df(a.Ea,a.Ca.O1[b.getMonth()]);a.Ya&&s_Df(a.Ya,a.Rb.format(b));var c=b.xY();s_wHb(b);b.add(new s_1w("m",-1));b.setDate(s_wHb(b)-(c-1));c=new s_1w("d",1);a.Ka=[];for(var d=0;6>d;d++){a.Ka[d]=[];for(var e=0;7>e;e++){a.Ka[d][e]=b.clone();var f=b.getFullYear();b.add(c);0==b.getMonth()&&1==b.getDate()&&f++;b.setFullYear(f)}}s_6jc(a)}},s_6jc=function(a){if(a.Fa()){var b=a.wa.getMonth(),c=new s_2w,d=
c.getFullYear(),e=c.getMonth();c=c.getDate();for(var f=6,g=0;6>g;g++){a.bua?(s_Df(a.Da[g+1][0],a.Wg.format(a.Ka[g][0])),s_mi(a.Da[g+1][0],a.Vh()+"-week")):(s_Df(a.Da[g+1][0],""),s_mi(a.Da[g+1][0],""));for(var h=0;7>h;h++){var k=a.Ka[g][h],l=a.Da[g+1][h+1];l.id||(l.id=s_L2b(a.Aub));s_fo(l,"gridcell");s_ZTa(l,a.Ig.format(k));var m=[a.Vh()+"-date"];a.RUa.contains(k)||m.push(a.Vh()+"-unavailable-date");k.getMonth()!=b&&m.push(a.Vh()+"-other-month");var n=(h+a.wa.ZX()+7)%7;a.wb[n]&&m.push(a.wb[n]);k.getDate()==
c&&k.getMonth()==e&&k.getFullYear()==d&&m.push(a.Vh()+"-today");a.Aa&&k.getDate()==a.Aa.getDate()&&k.getMonth()==a.Aa.getMonth()&&k.getFullYear()==a.Aa.getFullYear()&&(m.push(a.Vh()+"-selected"),a.qg=l);a.Vla&&(n=a.Vla(k))&&m.push(n);k=a.Df.format(k);s_Df(l,k);s_mi(l,m.join(" "))}4<=g&&(h=a.Da[g+1][0].parentElement||a.Da[g+1][0].parentNode,l=a.Ka[g][0].getMonth()==b,s_M(h,l||a.Vta),l||(f=Math.min(f,g)))}b=(a.Vta?6:f)+(a.cua?1:0);a.Vb!=b&&(a.Vb<b&&a.dispatchEvent("gridSizeIncrease"),a.Vb=b)}},s_0jc=
function(a){var b=new s_2jc("changeActiveMonth",a,a.wa.clone());a.dispatchEvent(b)},s_3jc=function(a){if(a.Fa()){if(a.cua)for(var b=0;7>b;b++){var c=a.Da[0][b+1],d=(b+a.wa.ZX()+7)%7;s_Df(c,a.Gc[(d+1)%7])}s_M(a.Da[0][0].parentElement||a.Da[0][0].parentNode,a.cua)}},s_4jc=function(a,b){var c=s_Ib(b);c in a.Ra||(a.Ra[c]=new s_2A(b));return a.Ra[c]},s_2jc=function(a,b,c){s_Tf.call(this,a,b);this.date=c};s_p(s_2jc,s_Tf);

s_h().wa();

}catch(e){_DumpException(e)}
try{
s_P("sy13v");
var s_xV=function(a){this.wa=[];this.Aa=s_0w;if("number"==typeof a){11<a&&(a=10);if(4>a)var b=this.Aa.NV[a];else 8>a?b=this.Aa.WQ[a-4]:(b=this.Aa.Twa[a-8],b=b.replace("{1}",this.Aa.NV[a-8]),b=b.replace("{0}",this.Aa.WQ[a-8]));s_6vf(this,b)}else s_6vf(this,a)},s_6vf=function(a,b){for(var c=!1,d="",e=0;e<b.length;e++){var f=b.charAt(e);if(" "==f)for(0<d.length&&(a.wa.push({text:d,count:0,Q1:!1}),d=""),a.wa.push({text:" ",count:0,Q1:!1});e<b.length-1&&" "==b.charAt(e+1);)e++;else if(c)"'"==f?e+1<b.length&&
"'"==b.charAt(e+1)?(d+="'",e++):c=!1:d+=f;else if(0<="GyMdkHmsSEDahKzZvQL".indexOf(f)){0<d.length&&(a.wa.push({text:d,count:0,Q1:!1}),d="");var g=b.charAt(e);for(var h=e+1;h<b.length&&b.charAt(h)==g;)h++;g=h-e;a.wa.push({text:f,count:g,Q1:!1});e+=g-1}else"'"==f?e+1<b.length&&"'"==b.charAt(e+1)?(d+="'",e++):c=!0:d+=f}0<d.length&&a.wa.push({text:d,count:0,Q1:!1});b=!1;for(c=0;c<a.wa.length;c++)s_7vf(a.wa[c])?!b&&c+1<a.wa.length&&s_7vf(a.wa[c+1])&&(b=!0,a.wa[c].Q1=!0):b=!1};
s_xV.prototype.parse=function(a,b,c){return s_8vf(this,a,b,c||0,!1)};
var s_9vf=function(a,b,c){return s_8vf(a,b,c,0,!0)},s_8vf=function(a,b,c,d,e){for(var f=new s_$vf,g=[d],h=-1,k=0,l=0,m=0;m<a.wa.length;m++)if(0<a.wa[m].count)if(0>h&&a.wa[m].Q1&&(h=m,k=d,l=0),0<=h){var n=a.wa[m].count;if(m==h&&(n-=l,l++,0==n))return 0;s_awf(a,b,g,a.wa[m],n,f)||(m=h-1,g[0]=k)}else{if(h=-1,!s_awf(a,b,g,a.wa[m],0,f))return 0}else{h=-1;if(" "==a.wa[m].text.charAt(0)){if(n=g[0],s_bwf(b,g),g[0]>n)continue}else if(b.indexOf(a.wa[m].text,g[0])==g[0]){g[0]+=a.wa[m].text.length;continue}return 0}a:{if(null==
c)throw Error("vi");void 0!=f.era&&void 0!=f.year&&0==f.era&&0<f.year&&(f.year=-(f.year-1));void 0!=f.year&&c.setFullYear(f.year);a=c.getDate();c.setDate(1);void 0!=f.month&&c.setMonth(f.month);void 0!=f.day?c.setDate(f.day):(b=s_rHb(c.getFullYear(),c.getMonth()),c.setDate(a>b?b:a));s_Ca(c.setHours)&&(void 0==f.hours&&(f.hours=c.getHours()),void 0!=f.Aa&&0<f.Aa&&12>f.hours&&(f.hours+=12),c.setHours(f.hours));s_Ca(c.setMinutes)&&void 0!=f.minutes&&c.setMinutes(f.minutes);s_Ca(c.setSeconds)&&void 0!=
f.Fp&&c.setSeconds(f.Fp);s_Ca(c.setMilliseconds)&&void 0!=f.wa&&c.setMilliseconds(f.wa);if(e&&(void 0!=f.year&&f.year!=c.getFullYear()||void 0!=f.month&&f.month!=c.getMonth()||void 0!=f.day&&f.day!=c.getDate()||24<=f.hours||60<=f.minutes||60<=f.Fp||1E3<=f.wa))c=!1;else{void 0!=f.pva&&(e=c.getTimezoneOffset(),c.setTime(c.getTime()+6E4*(f.pva-e)));f.Ba&&(e=new Date,e.setFullYear(e.getFullYear()-80),c.getTime()<e.getTime()&&c.setFullYear(e.getFullYear()+100));if(void 0!=f.Tla)if(void 0==f.day)f=(7+f.Tla-
c.getDay())%7,3<f&&(f-=7),e=c.getMonth(),c.setDate(c.getDate()+f),c.getMonth()!=e&&c.setDate(c.getDate()+(0<f?-7:7));else if(f.Tla!=c.getDay()){c=!1;break a}c=!0}}return c?g[0]-d:0},s_7vf=function(a){if(0>=a.count)return!1;var b="MydhHmsSDkK".indexOf(a.text.charAt(0));return 0<b||0==b&&3>a.count},s_bwf=function(a,b){(a=a.substring(b[0]).match(/^\s+/))&&(b[0]+=a[0].length)},s_awf=function(a,b,c,d,e,f){s_bwf(b,c);var g=c[0],h=d.text.charAt(0),k=-1;if(s_7vf(d))if(0<e){if(g+e>b.length)return!1;k=s_cwf(a,
b.substring(0,g+e),c)}else k=s_cwf(a,b,c);switch(h){case "G":return k=s_yV(b,c,a.Aa.Uwa),0<=k&&(f.era=k),!0;case "M":case "L":a:{d=k;if(0>d){d=s_yV(b,c,a.Aa.ika.concat(a.Aa.O1,a.Aa.ixa,a.Aa.lxa));if(0>d){f=!1;break a}f.month=d%12}else f.month=d-1;f=!0}return f;case "E":return d=s_yV(b,c,a.Aa.oxa),0>d&&(d=s_yV(b,c,a.Aa.kxa)),0>d?f=!1:(f.Tla=d,f=!0),f;case "a":return k=s_yV(b,c,a.Aa.Rwa),0<=k&&(f.Aa=k),!0;case "y":a:{if(0>k){var l=b.charAt(c[0]);if("+"!=l&&"-"!=l){f=!1;break a}c[0]++;k=s_cwf(a,b,c);
if(0>k){f=!1;break a}"-"==l&&(k=-k)}l||2!=c[0]-g||2!=d.count?f.year=k:(a=k,b=(new Date).getFullYear()-80,c=b%100,f.Ba=a==c,a+=100*Math.floor(b/100)+(a<c?100:0),f.year=a);f=!0}return f;case "Q":return 0>k?(d=s_yV(b,c,a.Aa.gxa),0>d&&(d=s_yV(b,c,a.Aa.jxa)),0>d?f=!1:(f.month=3*d,f.day=1,f=!0)):f=!1,f;case "d":return 0<=k&&(f.day=k),!0;case "S":return a=c[0]-g,f.wa=3>a?k*Math.pow(10,3-a):Math.round(k/Math.pow(10,a-3)),!0;case "h":12==k&&(k=0);case "K":case "H":case "k":return 0<=k&&(f.hours=k),!0;case "m":return 0<=
k&&(f.minutes=k),!0;case "s":return 0<=k&&(f.Fp=k),!0;case "z":case "Z":case "v":b.indexOf("GMT",c[0])==c[0]&&(c[0]+=3);a:if(c[0]>=b.length)f.pva=0,f=!0;else{d=1;switch(b.charAt(c[0])){case "-":d=-1;case "+":c[0]++}g=c[0];k=s_cwf(a,b,c);if(0>k)f=!1;else{if(c[0]<b.length&&":"==b.charAt(c[0])){l=60*k;c[0]++;k=s_cwf(a,b,c);if(0>k){f=!1;break a}l+=k}else l=k,l=24>l&&2>=c[0]-g?60*l:l%100+l/100*60;f.pva=-(l*d);f=!0}}return f;default:return!1}},s_cwf=function(a,b,c){if(a.Aa.sxa){for(var d=[],e=c[0];e<b.length;e++){var f=
b.charCodeAt(e)-a.Aa.sxa;d.push(0<=f&&9>=f?String.fromCharCode(f+48):b.charAt(e))}b=d.join("")}else b=b.substring(c[0]);a=b.match(/^\d+/);if(!a)return-1;c[0]+=a[0].length;return parseInt(a[0],10)},s_yV=function(a,b,c){var d=0,e=-1;a=a.substring(b[0]).toLowerCase();for(var f=0;f<c.length;f++){var g=c[f].length;g>d&&0==a.indexOf(c[f].toLowerCase())&&(e=f,d=g)}0<=e&&(b[0]+=d);return e},s_$vf=function(){};

s_h().wa();

}catch(e){_DumpException(e)}
try{
var s_MRg=function(a,b){a.Vla=b};s_P("Uuupec");
var s_NRg=s_U("Uuupec");
var s_ORg=s_nHb.NV[3],s___=function(a){s_k.call(this,a.La);this.Aa=this.Pb=this.wa=null;this.Ca=!0;this.Da=this.getData("m").Sb()};s_o(s___,s_k);s___.Ha=s_k.Ha;s___.prototype.Nc=function(){this.$H();s_1f(window,"resize",this.Ba)};
var s_PRg=function(a,b){var c=new Date,d=new s_xV(s_ORg);b=s_Jc(b.value);if(0==b.length||s_9vf(d,b,c)!=b.length)a.Aa.tRa();else{a.Ca=!1;try{a.Aa.setDate(c)}finally{a.Ca=!0}}},s_QRg=function(a,b){var c=s_I("qomYCd",a.Pb);s_qi(c,"KbfSHd","OouJcb"!=b.id);s_O(function(){s_S(c,"lRiKjb");s_Nh(function(){s_T(c,"lRiKjb")})},150)},s_RRg=function(){var a=new Date(s_Oa());a.setDate(28);var b,c=new Date(s_Oa());return function(d){if(!b)a:{var e=s_I("goog-date-picker-head");if(e&&(e=s_$e("goog-date-picker-btn",
e))&&1<e.length){b=e[1];break a}b=null}b&&s_qi(b,"suap3e",Number(a)<=Number(d));return Number(d)<=Number(c)?null:"suap3e"}},s_TRg=function(a){var b=s_kf("DIV","UfY8P");s_of(s_I("NwEGxd",a.Pb),b);var c=new s_PE;s_Yjc(c);c.aua=!1;c.kb&&s_Zjc(c);c.Vta=!0;s_QE(c);s__jc(c,!0);c.Gc=c.Ca.y9;s_3jc(c);s_Wjc(c);s_MRg(c,s_RRg());c.Xe(b);a.Aa=c;var d=s_I("Ru1Ao",a.Pb),e=s_e("OouJcb");b=s_e("rzG2be");s_K(c,"select",function(){var f=a.Aa.getDate();if(a.Ca&&f){var g=new s_6w(s_ORg.replace(/yy/,"y"));a.wa.value=
g.format(f);"OouJcb"==a.wa.id?s_e("rzG2be").focus():a.wa.focus()}});s_K(a.Pb,"keyup",function(f){27==f.keyCode&&a.$H()});s_K(e,"keydown",function(f){9==f.keyCode&&f.shiftKey&&(f.preventDefault(),d.focus())});s_K(d,"keydown",function(f){9!=f.keyCode||f.shiftKey||(f.preventDefault(),e.focus())});s_K(d,"click",function(){for(var f=[s_e("OouJcb"),s_e("rzG2be")],g=new Date,h=new s_xV(s_ORg),k=new s_6w(s_ORg.replace(/yy/,"y")),l=0;l<f.length;l++){var m=f[l],n=s_Jc(m.value);0!=n.length&&s_9vf(h,n,g)==n.length&&
(m.value=k.format(g))}});s_SRg(a,e);s_SRg(a,b);s_K(window,"resize",function(){return a.Ba()})};
s___.prototype.Ba=function(){if(this.Pb){var a=this.Pb,b=Math.max(s_I("tmDYm",a).clientWidth,s_I("iWBKNe",a).clientWidth),c=s_Dm()?"right":"left",d=s_I("J6UZg",a),e=s_wh(document.body||document.documentElement),f=s_wh(d),g=f.width+b;g<e.width?(d.style.width=g+"px",s_I("NwEGxd",a).style[c]=b+"px",s_T(d,"QIQ7Cc")):(d.style.width=e.width+"px",s_I("NwEGxd",a).style[c]="0",s_S(d,"QIQ7Cc"));this.Da?(a=s_Ll(0,!0),s_qh(d)+f.height<=a?d.style.top="":d.style.top=Math.max(0,a-f.height)+"px"):d.style.top="0"}};
var s_SRg=function(a,b){s_K(b,"keyup",function(c){s_PRg(a,b);27==c.keyCode&&a.$H()})};s___.prototype.ZK=function(a){this.wa=a=a.hb.el();s_QRg(this,a);s_PRg(this,a)};s___.prototype.$H=function(){this.Pb&&(this.Pb.style.display="none",this.wa=null)};s___.prototype.Lhc=function(a){(a=a.hb.el())&&s_URg(this,a)};
var s_URg=function(a,b){a.Pb||(b=s_I("n5Ug4b",b.parentElement),s_of(s_e("top_nav"),b),b.style.display="block",a.Pb=b,s_zi(a.Pb,a.Ja().el()),s_TRg(a));a.Pb.style.display="block";a.Ba();var c=s_e("OouJcb");s_PRg(a,c);s_Nh(function(){c.focus()})};s_X(s___.prototype,"EEGHee",function(){return this.Lhc});s_X(s___.prototype,"xp3IKd",function(){return this.$H});s_X(s___.prototype,"daRB0b",function(){return this.ZK});s_Y(s_NRg,s___);

s_h().wa();

}catch(e){_DumpException(e)}
try{
s_P("r36a9c");
var s_TZa=s_U("r36a9c");
var s_UZa=function(a){return null!=a&&0<a.getBoundingClientRect().width&&0<a.getBoundingClientRect().height?(a=window.getComputedStyle(a,null),"none"!==a.display&&"hidden"!==a.visibility&&"auto"===a.clip):!1},s_VZa=function(a){s_k.call(this,a.La)};s_o(s_VZa,s_k);s_VZa.Ha=s_k.Ha;
s_VZa.prototype.dNb=function(){var a=this.Fa("BKxS1e").el();s_g(a);a=s_Wi(this.zH().documentElement).find('[role="heading"], h1, h2, h3').filter(s_UZa).Ie();if(!s_Ff(a.el())){if(null==s_Ri(a,"aria-label")&&null==s_Ri(a,"aria-describedby")){var b=a.parent();if(s_UZa(b.el())&&"A"==b.el().tagName){b.focus();return}b=a.children().filter(s_UZa);if(1==b.size()&&"A"==b.Ie().el().tagName){b.Ie().focus();return}}a.el().tabIndex="-1";a.el().onblur=function(c){c.target.removeAttribute("tabIndex")}}a.focus()};
s_X(s_VZa.prototype,"i3viod",function(){return this.dNb});s_Y(s_TZa,s_VZa);

s_h().wa();

}catch(e){_DumpException(e)}
try{
var s_JNh=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c)>>>0;return b};s_P("xj7LNb");
var s_KNh=s_Q("m5ueAd");
var s_LNh=s_U("xj7LNb");
var s_x6=function(a){s_k.call(this,a.La);if(this.Ba=this.Ja().getData("cs").Bc())this.Da=[],this.Aa="",this.wa=this.Ja().getData("iae").Fb(0),this.Ca=Promise.resolve(),this.FLa=[],this.Ea=Promise.resolve(),s_MNh(this,this.Ja(),this.Qa("xXq91c"))};s_o(s_x6,s_k);s_x6.Ha=s_k.Ha;s_x6.prototype.Yqb=function(){s_NNh(this)};s_x6.prototype.hW=function(a){var b=s_4l(this,a.targetElement,"xXq91c");a=s_4l(this,a.targetElement,"oQYOj");s_f([new s_N(a.el(),"hide")],{triggerElement:b.el(),userAction:3})};
s_x6.prototype.b$=function(a){var b=this,c=s_4l(this,a.targetElement,"xXq91c"),d=s_4l(this,a.targetElement,"oQYOj");s_f([new s_N(d.el(),"show")],{triggerElement:c.el()});if(this.Ba){d=this.Da.indexOf(c.el());var e=this.Ja().getData("mqac").Fb(0);if(!(0<e&&d>=e)){var f=s_ONh(this),g=s_Wi(a.targetElement.closest(".related-question-pair"));s_FOa(f,this.Ja());f.setStyle({display:"block","transition-duration":"300ms"});var h=s_fb(300);h.then(function(){return f.setStyle({opacity:1,transform:"none"})});
this.Ca=this.Ca.then(function(){return s_PNh(b,c,f,g,h)})}}};
var s_MNh=function(a,b,c){a.Aa=b.getData("cs").Va();c.ud(function(e){return a.Da.unshift(e)});if(0<a.wa){b=b.getData("mqc").Fb();var d=s_JNh(s_4g().get("q")+a.wa.toString());(c=c.xd(d%(c.size()+b)))?(--a.wa,c.click()):a.wa=0}},s_PNh=function(a,b,c,d,e){var f,g,h,k,l,m,n,p;return s_Cb(function(q){switch(q.wa){case 1:return f=s_Pi(b),g=b.getData("kt"),h=new Map,h.set("q",f),h.set("state",a.Aa+"."+g),a.getData("sgrdEnabled").Bc()&&s_Fi(s_Vi(a.Ja().parent()),s_KNh,{context:h,triggerElement:b.el()}),s_yb(q,
2),q.Eb(s_vm(a.Ja().el(),h),4);case 4:s_zb(q,3);break;case 2:k=s_Ab(q),s_ba(k instanceof Error?k:Error(k));case 3:if(!a.Qa("sM5MNb").el())return a.wa=0,c.remove(),q.return();l=a.Fa("sM5MNb");m=s_3l(a,l,"xXq91c");n=l.Yf().offsetHeight;p=l.remove().children();c.before(p).setStyle({"border-width":(n-c.Yf().clientHeight)/2+"px 0","margin-top":-n+"px"});e.then(function(){a.FLa.push({WSa:c,Ys:p});s_NNh(a)});s_f(p.map(function(r){return new s_N(r,"show")}),{triggerElement:d.el(),userAction:1,data:{irq:f}});
s_MNh(a,l,m);s_xb(q)}})},s_NNh=function(a){a.Ea=a.Ea.then(function(){var b,c,d,e,f;return s_Cb(function(g){switch(g.wa){case 1:if(0==a.FLa.length)return g.return();b=s_b(a.FLa.splice(0,1));c=b.next().value;d=c.WSa;e=c.Ys;d.setStyle({opacity:"",transform:""});s_O(function(){return d.remove()},300);f=0;case 2:if(!(f<e.size())){g.Nd(4);break}e.xd(f).children().setStyle({opacity:1,transform:"none","transition-duration":"300ms"});return g.Eb(s_fb(100),3);case 3:++f;g.Nd(2);break;case 4:s_O(function(){return s_Bm(s_Cm.$j)},
300),s_NNh(a),s_xb(g)}})})};s_X(s_x6.prototype,"o7YQ2",function(){return this.b$});s_X(s_x6.prototype,"NlNJyb",function(){return this.hW});s_X(s_x6.prototype,"A6ecOd",function(){return this.Yqb});var s_ONh=function(a){return s_Wi(a.Fa("aZ2wEe").el().cloneNode(!0))};s_Y(s_LNh,s_x6);

s_h().wa();

}catch(e){_DumpException(e)}
// Google Inc.
