if (NOT DEFINED BALBINO_DIR)
    message(FATAL_ERROR "BALBINO_DIR is not defined.")
endif ()

set_property(GLOBAL PROPERTY USE_FOLDERS ON)

if (NOT DEFINED PROJECT_DIR)
    set(PROJECT_DIR "${CMAKE_SOURCE_DIR}")
endif ()

set(CMAKE_C_STANDARD 17)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

if (NOT CYGWIN)
    set(CMAKE_CXX_EXTENSIONS OFF)
endif ()
