name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: ${{matrix.os}}, ${{matrix.build_type}}, ${{matrix.platform}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ windows-latest, linux-latest ]
        build_type: [ Windows-Debug, Windows-DebugEditor, Windows-Release, Windows-ReleaseEditor ]

    steps:
      - uses: actions/checkout@v4

      - name: Initialize Submodules
        run: git submodule update --init --recursive

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: 1.3.243.0
          cache: true

      - name: Run Setup Script
        run: ${{github.workspace}}/Scripts/install-vulkan.ps1 # Run your setup script

      - name: Configure CMake
        run: cmake --preset ${{matrix.build_type}} -S ${{github.workspace}} -B ${{github.workspace}}/Build/

      - name: Build
        run: cmake --build --target Deer --preset ${{matrix.build_type}} --parallel %NUMBER_OF_PROCESSORS%